# Generated by Django 5.2.14 on 2026-05-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyverse_donation_referral_prayerlog_streaklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('scripture_reference', models.CharField(max_length=120)),
                ('scripture_text', models.TextField()),
                ('reflection', models.TextField()),
                ('prayer_prompt', models.TextField()),
                ('journal_prompt', models.TextField()),
                ('date', models.DateField(unique=True)),
                ('season', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='prayerlog',
            name='category',
            field=models.CharField(choices=[('thanksgiving', 'Thanksgiving'), ('confession', 'Confession'), ('petition', 'Petition'), ('intercession', 'Intercession'), ('healing', 'Healing'), ('family', 'Family'), ('work_school', 'Work or School'), ('nation', 'Nation'), ('church', 'Church'), ('answered_prayer', 'Answered Prayer')], default='petition', max_length=30),
        ),
    ]
