# Generated by Django 5.2.14 on 2026-05-17 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_biblebook_prayerplan_prayerlog_testimony_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.prayergroup'),
        ),
    ]
