# Generated by Django 5.2.14 on 2026-05-17 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prayerlog_testimony_note_prayerlog_verse_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('days', models.PositiveIntegerField(default=7)),
                ('theme', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BibleReadingPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('passage_reference', models.CharField(max_length=120)),
                ('passage_text', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('prayer_prompt', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_days', to='core.biblereadingplan')),
            ],
            options={
                'ordering': ('plan', 'day_number'),
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='GroupGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('goal_type', models.CharField(choices=[('prayer_count', 'Prayer count'), ('member_coverage', 'Member coverage'), ('request_coverage', 'Request coverage')], default='prayer_count', max_length=30)),
                ('target_count', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.prayergroup')),
            ],
            options={
                'ordering': ('-is_active', 'end_date'),
            },
        ),
        migrations.CreateModel(
            name='PublicTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(max_length=1000)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amen_by', models.ManyToManyField(blank=True, related_name='amen_testimonies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserBibleReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.biblereadingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='BibleReadingPlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.biblereadingplanday')),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_days', to='core.userbiblereadingplan')),
            ],
            options={
                'ordering': ('-completed_at',),
                'unique_together': {('user_plan', 'plan_day')},
            },
        ),
    ]
