from django.urls import path

from . import views


urlpatterns = [
    path("sw.js", views.service_worker, name="service_worker"),
    path("", views.home_view, name="home"),
    path("community/", views.prayer_board_view, name="prayer_board"),
    path("community/pray/<int:pk>/", views.pray_for_view, name="pray_for"),
    path("community/request/<int:pk>/status/", views.prayer_request_status_view, name="prayer_request_status"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("pray/simple/", views.simple_pray_view, name="simple_pray"),
    path("bible/", views.bible_book_view, name="bible"),
    path("bible/<str:abbreviation>/", views.bible_book_view, name="bible_book"),
    path("donate/", views.donate_view, name="donate"),
    path("family/", views.family_view, name="family"),
    path("family/create/", views.create_family_view, name="create_family"),
    path("family/join/", views.join_family_view, name="join_family"),
    path("family/pray/<int:pk>/", views.family_pray_view, name="family_pray"),
    path("family/request/<int:pk>/answered/", views.family_mark_answered_view, name="family_mark_answered"),
    path("invite/", views.invite_view, name="invite"),
    path("journal/", views.journal_view, name="journal"),
    path("journal/<int:pk>/", views.journal_detail_view, name="journal_detail"),
    path("journal/<int:pk>/answered/", views.mark_answered_view, name="journal_mark_answered"),
    path("journal/export/filtered.csv", views.journal_export_csv_view, name="journal_export_csv"),
    path("journal/export/filtered.pdf", views.journal_export_pdf_view, name="journal_export_pdf"),
    path("leaderboard/", views.leaderboard_view, name="leaderboard"),
    path("onboarding/", views.onboarding_view, name="onboarding"),
    path("profile/", views.profile_view, name="profile"),
    path("prayer/<int:pk>/answered/", views.mark_answered_view, name="mark_answered"),
    path("journal/export.csv", views.export_journal_csv_view, name="export_journal_csv"),
    path("settings/", views.routine_settings_view, name="settings"),
    path("settings/push-subscription/", views.save_push_subscription_view, name="save_push_subscription"),
    path("settings/reminder/<int:pk>/delete/", views.delete_reminder_view, name="delete_reminder"),
    path("plans/<int:pk>/start/", views.start_prayer_plan_view, name="start_prayer_plan"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]
